### ISSUE TITLE
File not found error in validator call in sbol3 to 2 conversion

### ISSUE THREAD

**Issue by JMante1** [SynBioDex/SBOL-utilities#300]
sbol_utilities\conversion.py", line 237, in convert3to2
    result = doc2.validate()
  sbol2\document.py", line 831, in validate
    response = validate(self, config.options)
sbol2\document.py", line 1128, in validate
    result = do_validation(json_request)
sbol2\validator.py", line 174, in do_validation
    result = run.execute()
sbol2\validator.py", line 64, in execute
    output = subprocess.check_output(command, universal_newlines=True, stderr=subprocess.STDOUT)
subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
 subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by jakebeal** [comment]
I need more information than this to be able to reproduce and debug the error.

**Comment by JMante1** [comment]
I can give you this code and the file being read in but not sure it will necessarily help you reproduce the error:

`from sbol_utilities import conversion
import sbol3


doc3 = sbol3.Document()
doc3.read("SBOL.xml")
doc2 = conversion.convert3to2(doc3)`

I have attached it but renamed it as json.
[SBOL.xml.json](https://github.com/user-attachments/files/16950221/SBOL.xml.json)

**Comment by JMante1** [comment]
Were you able to recreate the error? I think this relates: https://stackoverflow.com/questions/73193119/python-filenotfounderror-winerror-2-the-system-cannot-find-the-file-specifie

**Comment by jakebeal** [comment]
I was not able to reproduce the error, though I did get a validation error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jbeal/Library/Python/3.9/lib/python/site-packages/sbol_utilities/conversion.py", line 239, in convert3to2
    raise ValueError(f'Conversion from SBOL3 to SBOL2 produced an invalid document: {result}')
ValueError: Conversion from SBOL3 to SBOL2 produced an invalid document: Invalid. sbol-10403: Strong Validation Error: The encoding property of Sequence is REQUIRED and MUST contain a URI. Reference: SBOL Version 2.3.0 Section 7.6 on page 20 : http://sbols.org/unspecified_namespace/Bigger_toolkit_seq  Validation failed.
```

This capability is known to work on windows - it's part of the standard CI testing, so my suspicion is that it's likely to be something to do with the differences between your installation environment and the GitHub Windows test environment.

What versions of the libraries do you have installed?
According to pip, I am running 
```
sbol-utilities                1.0a17
sbol2                         1.4.1
sbol3                         1.1
```

**Comment by JMante1** [comment]
I am using those same versions. Maybe something else installed is interferring?

**Comment by jakebeal** [comment]
This error makes me think that it's not being able to find the binary required to be installed by the converter. 

I notice that your error says "sbol_utilities\conversion.py", a relative path, rather than an absolute path in the installed site packages. Did you pip install the package, and is that what's actually being run?

**Comment by jakebeal** [comment]
With no response for 6 months, I am going to assume @JMante1 was able to resolve this issue on their own. If not, please reopen.
