### ISSUE TITLE
Installing sbol-utilities via pip does not add graphviz to system path

### ISSUE THREAD

**Issue by noahsprent** [SynBioDex/SBOL-utilities#44]
System: Ubuntu Linux 20.04.3

Steps to reproduce:
- Create conda virtual environment, python version 3.9
- Run `pip install sbol-utilities`
- In python interpreter:

```
Python 3.9.7 (default, Sep 16 2021, 13:09:58) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sbol3
>>> from sbol_utilities.graph_sbol import graph_sbol
>>> doc = sbol3.Document()
>>> graph_sbol(doc)
Traceback (most recent call last):
  File "/home/nls119/lib/miniconda3/envs/sbol_utils/lib/python3.9/site-packages/graphviz/backend.py", line 170, in run
    proc = subprocess.Popen(cmd, startupinfo=get_startupinfo(), **kwargs)
  File "/home/nls119/lib/miniconda3/envs/sbol_utils/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/nls119/lib/miniconda3/envs/sbol_utils/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'dot'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nls119/lib/miniconda3/envs/sbol_utils/lib/python3.9/site-packages/sbol_utilities/graph_sbol.py", line 51, in graph_sbol
    dot_master.render(outfile, view=True)
  File "/home/nls119/lib/miniconda3/envs/sbol_utils/lib/python3.9/site-packages/graphviz/files.py", line 238, in render
    rendered = backend.render(self._engine, format, filepath,
  File "/home/nls119/lib/miniconda3/envs/sbol_utils/lib/python3.9/site-packages/graphviz/backend.py", line 235, in render
    run(cmd, capture_output=True, cwd=cwd, check=True, quiet=quiet)
  File "/home/nls119/lib/miniconda3/envs/sbol_utils/lib/python3.9/site-packages/graphviz/backend.py", line 173, in run
    raise ExecutableNotFound(cmd) from e
graphviz.backend.ExecutableNotFound: failed to execute 'dot', make sure the Graphviz executables are on your systems' PATH
```
However, installing graphviz from conda ```conda install graphviz``` fixes this.

**Comment by jakebeal** [comment]
@bbartley This issue is beyond my current knowledge of python requirements management --- do you know a good path to resolving it?

**Comment by tcmitchell** [comment]
I don't think there's anything sbol-utilities can do about this. The python graphviz package requires a working installation of Graphviz (see https://graphviz.readthedocs.io/en/stable/manual.html#installation). Conda must automatically install that as part of the conda packaging of the graphviz python package.

I get the same error in a python interpreter if I just `pip install graphviz`. I do not have [Graphviz](https://www.graphviz.org) installed.

Maybe this is a documentation issue. Explain that if a user is going to use `graph_sbol` they'll need a working installation of Graphviz.

graph_sbol could also catch this error and provide a better message to the user, like recommending an installation of Graphviz.

**Comment by jakebeal** [comment]
I've added documentation addressing this with pull #54
